---
- hosts: 172.31.21.192
  become: yes
  tasks:
  - name: I want to execute linux commands
    command: hostname -f
    register: myresult
  - name: I want to dispaly command result
    debug:
      msg: "{{myresult}}"  
