---
- hosts: all
  become: yes
  tasks:
  - name: ping all nodes
    ping:
  - name: install apache webserver
    apt:
     name: apache2
     state: present
    when:  ansible_os_family == "Debian"  
  - name: install git
    yum:
     name: git
     state: present
    when:  ansible_os_family == "RedHat"