---
- hosts: 172.31.21.192
  become: yes
  tasks:
  - name: I want to handle file
    file:
      path: /home/ubuntu/myubuntufile
      state: touch
  - include_tasks: myfile.yml    

  - name : I want to instal webserver
    apt:
      name: apache2
      state: present