---
- name: I want to copy tomcat user file into ubuntu node
  template:
    src: templates/tomuser.j2
    dest: /opt/tomcat/conf/tomcat-users.xml
- name: I want to copy tomcat manager context file into ubuntu node
  template:
    src: templates/managercontext.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml  

- name: I want to copy tomcat host manager context file into ubuntu node
  template:
    src: templates/hostmanagercontext.j2
    dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml      