---
- name: I want to copy Tomcat Web Management file into ubuntu node
  template:
    src: templates/tomuser.j2
    dest: /opt/tomcat/conf/tomcat-users.xml
- name: I want to copy Tomcat manager context file into ubuntu node
  template:
    src: templates/managercontext.j2
    dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml     