---
# tasks file for mywebrole
- name: I want to install webserver
  apt:
    name: apache2
    state: present
- name: I want to copy index file to node side
  template:
    src: templates/index.j2
    dest: /var/www/html/index.html